module.exports =  {
  is: "project",
  name: "Repository",
  workspace: "logitud.repository",
  "files=": { is: 'group', elements: [
      { is: 'group', name: 'app', path: 'app/src/', elements: [
        { is: 'file', name: 'main.ts', tags: ['tsc'] },
        { is: 'file', name: 'index.html', tags: ['copy'] },
        { is: 'file', name: 'styles.css', tags: ['copy'] },
        { is: 'file', name: 'systemjs.config.js', tags: ['copy'] },
        { is: 'file', name: 'images/*.png', tags: ['copy'] },
      ]},
      { is: 'group', name: 'server', path: 'server/src/', elements: [
        { is: 'file', name: 'server.ts', tags: ['tsc']},
      ]},
      { is: 'group', name: 'shared', path: 'shared/src/', elements: [
        { is: 'file', name: 'interfaces.md', tags: ['interface']},
      ]},
  ]},
  "targets=": { is: 'group',
    "repository app=":  {
      is: 'target',
      environments: ["=::openms.aspects.angular::"],
      files: ["=files:app ? tsc", "=files:shared ? tsc"],
      copyFiles: [{ is: "group", elements: ["=files:app ? copy"], dest: "", expand: true }],
      interfaces: [{ is: "group", elements: ['=files:shared ? interface'] }],
      npmPackage: { is: "component",
        dependencies: { is: "component",
          "@openmicrostep/async": "^0.1.1",
        },
      },
    },
    "repository server=":  {
      is: 'target',
      environments: ["=::openms.aspects.node::"],
      files: ["=files:server ? tsc", "=files:shared ? tsc"],
      interfaces: [{ is: "group", elements: ['=files:shared ? interface'] }],
      npmPackage: { is: "component",
        dependencies: { is: "component",
          "sqlite3": "^3.1.8",
          "pg": "^7.3.0",
          "mongodb": "^2.2.31",
          "request": "^2.83.0",
          "request-promise-native": "^1.0.5",
          "express-session": "^1.15.6",
          "connect-mongo": "^1.3.2",
          "ldapjs": "^1.0.1",
          "body-parser": "^1.18.2",
          "@openmicrostep/msbuildsystem.shared": "^0.6.3",
          "source-map-support": "^0.4.11",
        },
        devDependencies: { is: "component",
          "@types/ldapjs": "^1.0.0",
          "@types/express-session": "^1.15.3",
          "@types/request-promise-native": "^1.0.8",
        },
      },
    }
  }
};
